Repository dooboolab/dooboo-frontend-ts, pull requests merged in 2019-07, with the labels that each got.

#30 Update packages
  package.json
Labels: updates

#34 Fix bug of eslint command
  package.json
Labels: bugfix

#37 Enhanced typings and linting rules
  .eslintrc.js
  README.md
  package.json
  src/App.tsx
  src/components/navigation/SwitchNavigator.tsx
  src/components/screen/Intro.tsx
  src/components/screen/Temp.tsx
  src/components/screen/__tests__/Intro.test.tsx
  src/components/shared/Button.tsx
  src/contexts/index.ts
  src/providers/AppProvider.tsx
  src/theme.ts
  src/types/index.ts
  src/utils/Functions.ts
  src/utils/Icons.ts
  yarn.lock
Labels: linting, typings

#38 Upgrade packages
  package.json
  yarn.lock
Labels: upgrade
