Repository dooboolab/dooboo-frontend-ts, pull requests merged in 2019-11, with the labels that each got.

#50 Add i18n-js localization and enh context pattern
  .eslintrc.js
  .gitignore
  README.md
  STRINGS.ts
  assets/langs/en.json
  assets/langs/ko.json
  package.json
  src/App.tsx
  src/components/navigation/SwitchNavigator.tsx
  src/components/screen/Intro.tsx
  src/components/screen/Temp.tsx
  src/components/screen/__tests__/Intro.test.tsx
  src/components/screen/__tests__/__snapshots__/Intro.test.tsx.snap
  src/components/shared/Button.tsx
  src/components/shared/__tests__/Button.test.tsx
  src/components/ui/Buttons.tsx
  src/contexts/index.ts
  src/providers/AppProvider.tsx
  src/providers/ThemeProvider.tsx
  src/providers/__tests__/AppProvider.test.tsx
  src/providers/__tests__/__snapshots__/AppProvider.test.tsx.snap
  src/providers/index.ts
  src/providers/index.tsx
  src/theme.ts
  src/types/index.ts
  src/utils/Functions.ts
  src/utils/Icons.ts
  src/utils/createCtx.ts
  tsconfig.json
  yarn.lock
Labels: enhancement, feature

#52 Refactor code base
  README.md
  environment.d.ts
  jest.config.js
  package.json
  src/apis/authApi.ts
  src/apis/memberApi.ts
  src/apis/sample.ts
  src/apis/urls.ts
  src/components/navigation/SwitchNavigator.tsx
  src/components/screen/Intro.tsx
  src/components/screen/Temp.tsx
  src/components/screen/__tests__/Intro.test.tsx
  src/components/screen/__tests__/Temp.test.tsx
  src/components/screen/__tests__/__snapshots__/Intro.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/Temp.test.tsx.snap
  src/components/shared/Button.tsx
  src/components/shared/__tests__/Button.test.tsx
  src/components/shared/__tests__/__snapshots__/Button.test.tsx.snap
  src/components/ui/Buttons.tsx
  src/utils/Icons.ts
  test/testUtils.tsx
  tsconfig.json
  yarn.lock
Labels: refactor

#55 Circleci config
  .circleci/config.yml
Labels: ci
